version: 0.2

env:
  variables: 

phases:
  install:
    runtime-versions:
      dotnet: "8.0" 
    commands:
      - dotnet --info
  pre_build:
    commands:
      - dotnet restore
  build:
    commands:
      - dotnet build --configuration Release --no-restore
      - dotnet test --configuration Release --no-build --logger "trx;LogFileName=testresults.trx"
  post_build:
    commands:
      - mkdir -p artifact
      # publish the app (adjust path to your csproj if needed)
      - dotnet publish Lego/LegoEventService/LegoEventService.csproj -c Release -o artifact --no-build
artifacts:
  files:
    - '**/*'
  base-directory: artifact
  discard-paths: no
cache:
  paths:
    - '/root/.nuget/packages/**/*'    # Linux NuGet cache